Updated code

diff --git a/bin/nfs-mount b/bin/nfs-mount
--- a/bin/nfs-mount
+++ b/bin/nfs-mount
@@ -1,5 +1,28 @@
 #!/bin/sh
 
+<<<<<<< HEAD
+REMOTE_DIR=$1
+LOCAL_DIR=$2
+
+if [ -z "$REMOTE_DIR" -o -z "$LOCAL_DIR" ]
+then
+	echo Missing options. Try again and don\'t be a dumb-ass.
+	exit 1
+fi
+
+OS=$(uname -s)
+
+case $OS in
+	Darwin)
+		# It will fail to connect to Fedora without the "tcp" option.
+		# It will fail in general without the "resvport" option.
+		mount -t nfs -o tcp,resvport "$REMOVE_DIR" "$LOCAL_DIR"
+		;;
+	*)
+		echo Not yet
+		;;
+esac
+=======
 if [ `uname -s` = 'Darwin' ]
 then
     REMOTE_DIR=$1
@@ -17,4 +40,5 @@ then
 else
     echo This is only for MacOS X 10.4.11 which requires silly options to work.
 fi
+>>>>>>> 7748b23a917bc72d2fc1f060ed3873cae4f41480
 
